In [2]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_api

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Tukrah,LY,32.53,20.58,70.02,44,0,10.89
1,1,East London,ZA,-33.02,27.91,71.60,73,0,8.05
2,2,Turkistan,KZ,43.00,68.00,68.07,61,49,11.70
3,3,Vaini,TO,-21.20,-175.20,78.80,94,75,10.29
4,4,Bathsheba,BB,13.22,-59.52,86.00,62,20,21.92

In [4]:
# One caveat to using gmaps: The data we use for any mapping must be either an integer 
# or a floating-point decimal number. Letâ€™s check the data types for the columns of our DataFrame.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [5]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_api)

In [6]:
# # The general syntax for creating a heatmap is as follows.

# # 1. Assign the locations to an array of latitude and longitude pairs.
# locations = [latitude, longitude]
# # 2. Assign the weights variable to some values.
# temperatures = # an array of equal length of the locations array.
# # 3. Assign the figure variable to the gmaps.figure() attribute.
# fig = gmaps.figure()
# # 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
# heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# # 5. Add the heatmap layer.
# fig.add_layer(heatmap_layer)
# # 6. Call the figure to plot the data.
# fig

In [8]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

temps

[70.02,
 71.6,
 68.07,
 78.8,
 86.0,
 96.51,
 63.0,
 78.8,
 85.1,
 47.37,
 69.8,
 51.8,
 42.8,
 51.91,
 70.36,
 84.2,
 84.2,
 69.8,
 69.01,
 80.6,
 41.0,
 41.0,
 78.01,
 81.0,
 79.0,
 53.51,
 46.99,
 85.24,
 40.89,
 37.99,
 81.21,
 57.99,
 42.8,
 75.06,
 52.0,
 71.6,
 51.8,
 52.0,
 87.8,
 87.8,
 26.8,
 41.0,
 78.8,
 32.0,
 73.6,
 58.23,
 48.29,
 17.6,
 79.23,
 52.0,
 80.87,
 82.4,
 74.34,
 80.6,
 95.97,
 63.0,
 84.43,
 79.34,
 86.36,
 29.98,
 82.9,
 80.06,
 77.02,
 32.2,
 33.53,
 61.14,
 80.01,
 10.4,
 57.2,
 103.28,
 52.0,
 89.6,
 44.65,
 64.0,
 72.0,
 23.0,
 51.03,
 43.0,
 72.34,
 100.8,
 82.08,
 80.85,
 72.99,
 21.2,
 75.87,
 75.15,
 23.0,
 63.18,
 61.0,
 80.28,
 39.2,
 66.2,
 44.01,
 69.8,
 43.0,
 38.68,
 26.65,
 64.99,
 33.73,
 42.8,
 32.05,
 97.43,
 78.48,
 81.3,
 57.2,
 43.0,
 71.6,
 76.73,
 78.49,
 87.8,
 68.29,
 62.96,
 24.8,
 53.24,
 32.0,
 83.71,
 75.52,
 37.99,
 75.51,
 73.6,
 78.94,
 75.2,
 73.4,
 72.0,
 79.79,
 50.0,
 35.51,
 87.58,
 53.01,
 30.0,
 78.8,
 28.98,
 64.4,
 39.2,
 62.6,
 82.4,
 51.8,
 74.05,
 78.8,
 77.0,
 78.8,
 82.98,
 57.2,
 48.99,
 69.21,
 80.6,
 80.1,
 55.99,
 69.33,
 48.2,
 66.07,
 57.0,
 51.8,
 62.87,
 70.45,
 98.6,
 84.2,
 39.31,
 75.43,
 79.2,
 86.0,
 32.41,
 79.79,
 81.32,
 68.63,
 41.0,
 66.0,
 54.68,
 77.0,
 68.92,
 77.92,
 80.6,
 73.4,
 39.0,
 88.0,
 30.34,
 73.4,
 76.08,
 75.69,
 105.94,
 84.0,
 73.2,
 55.99,
 83.35,
 81.03,
 82.89,
 69.46,
 39.2,
 38.57,
 20.52,
 44.6,
 68.7,
 93.52,
 107.98,
 66.2,
 44.6,
 87.39,
 32.0,
 33.8,
 51.01,
 52.0,
 37.26,
 84.22,
 65.52,
 81.64,
 39.47,
 33.06,
 84.0,
 79.39,
 46.99,
 86.07,
 67.37,
 66.97,
 77.0,
 69.8,
 63.64,
 37.4,
 42.62,
 12.2,
 48.2,
 79.27,
 42.8,
 33.58,
 81.16,
 85.62,
 67.59,
 73.4,
 73.4,
 37.4,
 55.4,
 25.05,
 77.0,
 76.73,
 78.8,
 78.8,
 37.0,
 28.92,
 101.53,
 59.0,
 80.28,
 60.22,
 71.6,
 33.8,
 77.47,
 33.8,
 49.5,
 55.99,
 82.9,
 71.6,
 61.32,
 55.4,
 72.0,
 75.36,
 64.99,
 80.92,
 66.99,
 41.0,
 70.3,
 28.4,
 65.5,
 35.55,
 84.2,
 14.61,
 55.49,
 80.01,
 32.13,
 75.0,
 87.8,
 57.36,
 46.0,
 39.67,
 62.6,
 28.4,
 83.57,
 15.12,
 59.54,
 86.0,
 76.62,
 59.0,
 62.6,
 84.2,
 82.76,
 68.16,
 64.4,
 72.0,
 55.54,
 42.8,
 71.01,
 73.4,
 72.37,
 52.34,
 77.0,
 75.33,
 28.4,
 81.55,
 89.69,
 71.4,
 18.48,
 59.52,
 63.0,
 80.58,
 82.87,
 75.99,
 58.48,
 81.72,
 32.07,
 48.56,
 46.0,
 66.0,
 30.99,
 46.4,
 62.6,
 61.61,
 91.98,
 32.23,
 39.2,
 84.2,
 91.4,
 82.74,
 86.22,
 54.0,
 85.89,
 82.54,
 32.0,
 67.6,
 84.2,
 39.2,
 41.0,
 83.52,
 79.97,
 76.14,
 80.26,
 73.4,
 78.64,
 47.39,
 77.0,
 30.38,
 19.98,
 44.6,
 34.2,
 73.4,
 72.07,
 34.95,
 66.99,
 33.8,
 65.44,
 84.2,
 74.55,
 66.47,
 74.68,
 66.2,
 48.99,
 82.99,
 31.51,
 35.6,
 79.23,
 54.84,
 45.95,
 57.2,
 66.2,
 30.29,
 83.41,
 82.45,
 86.13,
 58.75,
 62.6,
 62.6,
 34.09,
 89.73,
 86.77,
 103.39,
 82.06,
 85.71,
 48.2,
 82.31,
 25.27,
 82.0,
 77.68,
 59.0,
 45.0,
 86.47,
 59.02,
 35.08,
 55.4,
 55.4,
 79.36,
 55.4,
 63.27,
 63.52,
 59.95,
 105.46,
 48.2,
 39.2,
 90.77,
 83.84,
 47.98,
 53.01,
 48.99,
 24.49,
 81.55,
 81.84,
 69.15,
 69.8,
 63.0,
 41.76,
 82.27,
 78.01,
 87.73,
 33.03,
 88.45,
 78.8,
 76.42,
 84.99,
 82.83,
 84.88,
 77.94,
 84.51,
 41.0,
 91.4,
 39.0,
 80.6,
 82.35,
 48.99,
 57.0,
 108.5,
 35.01,
 60.01,
 77.27,
 75.2,
 35.01,
 61.0,
 32.0,
 87.8,
 63.95,
 60.8,
 71.6,
 64.0,
 67.71,
 101.73,
 36.79,
 57.0,
 51.8,
 78.58,
 57.4,
 42.01,
 72.16,
 75.2,
 53.73,
 86.0,
 77.0,
 42.46,
 31.48,
 71.6,
 78.48,
 57.65,
 64.99,
 54.36,
 45.7,
 62.6,
 61.0,
 81.07,
 86.65,
 71.01,
 68.0,
 58.86,
 77.0,
 68.0,
 86.0,
 69.94,
 75.2,
 66.2,
 83.01,
 93.02,
 37.4,
 80.6,
 86.56,
 82.4,
 71.01,
 83.97,
 81.93,
 52.0,
 71.6,
 84.34,
 89.6,
 57.0,
 82.0,
 58.03,
 48.42,
 78.8,
 75.87,
 59.0,
 84.02,
 91.22,
 78.8,
 61.0,
 68.0,
 66.99,
 75.2,
 60.8,
 82.38,
 81.09,
 86.0,
 64.92,
 53.6,
 80.6,
 78.8,
 62.6,
 78.01,
 110.3,
 35.6,
 67.37,
 105.04,
 77.13,
 59.49,
 73.44,
 65.34,
 39.2,
 66.99,
 48.2,
 85.08,
 74.08,
 78.8,
 68.43,
 69.8,
 62.6,
 80.35,
 84.65,
 84.99,
 50.31,
 79.59,
 107.6,
 81.43,
 55.33,
 84.2,
 39.99,
 84.2,
 60.01,
 64.99,
 73.4,
 43.92,
 73.4,
 86.0,
 50.0,
 69.8,
 80.89,
 58.15,
 82.24,
 74.34,
 53.01,
 63.0,
 63.88,
 46.0,
 87.8,
 63.64,
 70.0,
 83.98,
 87.84,
 34.72,
 39.99,
 75.2,
 78.84,
 55.99,
 72.72,
 90.18,
 74.98,
 85.55,
 68.38,
 67.15,
 69.57,
 83.79,
 37.0,
 73.4,
 85.35,
 32.0,
 104.0,
 28.83,
 70.38,
 77.02,
 39.16,
 70.75,
 84.83,
 94.44,
 66.99,
 67.28,
 64.4,
 50.13,
 72.75,
 25.14,
 82.4,
 33.8,
 50.0,
 82.22,
 60.55,
 51.8,
 73.4,
 39.4,
 105.8,
 83.7,
 54.36,
 69.4,
 82.4]

In [16]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0,31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating = False, max_intensity=300, point_radius = 4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# heatmap of percent cloudiness
locations = city_data_df[["Lat","Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,weights=clouds, dissipating = False, max_intensity = 300, point_radius =4)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# heatmap of percent cloudiness
locations = city_data_df[["Lat","Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,weights=wind, dissipating = False, max_intensity = 300, point_radius =4)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [31]:
# Recall that you use the input() statement to prompt a user to enter information.
# To convert the input to a floating-point decimal number,
# wrap the input() statement with the float() method, like this: float(input()).

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 78
What is the maximum temperature you would like for your trip? 90

In [32]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
3,3,Vaini,TO,-21.20,-175.20,78.80,94,75,10.29
4,4,Bathsheba,BB,13.22,-59.52,86.00,62,20,21.92
7,7,Mahebourg,MU,-20.41,57.70,78.80,69,40,9.17
8,8,Hithadhoo,MV,-0.60,73.08,85.10,78,100,14.63
15,15,San Cristobal,VE,7.77,-72.22,84.20,54,40,28.86
16,16,Georgetown,MY,5.41,100.34,84.20,94,20,4.70
19,19,Banjar,ID,-8.19,114.97,80.60,94,20,9.17
22,22,Grand Gaube,MU,-20.01,57.66,78.01,67,5,1.99
23,23,Hermanus,ZA,-34.42,19.23,81.00,48,0,1.01
24,24,Cape Town,ZA,-33.93,18.42,79.00,53,0,5.82

In [33]:
preferred_cities_df.count()

City_ID       164
City          164
Country       164
Lat           164
Lng           164
Max Temp      164
Humidity      164
Cloudiness    164
Wind Speed    164
dtype: int64

In [34]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp    Lat     Lng Hotel Name
3           Vaini      TO     78.80 -21.20 -175.20
4       Bathsheba      BB     86.00  13.22  -59.52
7       Mahebourg      MU     78.80 -20.41   57.70
8       Hithadhoo      MV     85.10  -0.60   73.08
15  San Cristobal      VE     84.20   7.77  -72.22
16     Georgetown      MY     84.20   5.41  100.34
19         Banjar      ID     80.60  -8.19  114.97
22    Grand Gaube      MU     78.01 -20.01   57.66
23       Hermanus      ZA     81.00 -34.42   19.23
24      Cape Town      ZA     79.00 -33.93   18.42

In [35]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_api,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

In [36]:
# call the hotels variable to look at the JSON data, we get the following at the top of the output.
hotels

{'html_attributions': [],
 'next_page_token': 'CqQCGwEAAJtxrJsjLuk81WtdkhIE2PBnZ6lBeyfTGEOe4j-5w_f-wVtn4-EgZpdAuaLrgaasHgwFtMMapNdyOHnXnNx6LU-qp1pMagVFiZMYP44n_oPPCGlmjE732ESnvmfNiGmocZGkeBAerq8c7yqAyNkNowBy7agrlGHjauNp9PWuxZVsBcXTvbUH6KEWOIXKrT8UZLL3J6FdWgyZbOgzRL1VvnrFkpepIhKlUNAgXvxyYAhvfvdcRApc0hX03rNEWJ2l1acyE3a10UJZ7kL9vxpCG6HDXd6jNobHpoa4LpL6VKx1_eyFNM0Y_KsSqmnPYRupVev7Mefjp6oLyknEujJJaBxwe9yaHXFJnS7z4g7f4SAR3AzKMsnbxanlaPNdektqKBIQD2Fn7sUgoxRCvjqHEVhsyxoUXEJAGq6iMqKoud7oI9W7g23sdvU',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594402302915,
      'lng': 2.354348530291502},
     'southwest': {'lat': 48.8567422697085, 'lng': 2.351650569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '7fa47cb61d7345cecc3b802d0e04fcff2b3d5ecb',
   'name': 'HÃ´tel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">HÃ´tel Duo</a>'],
     'photo_reference': 'CmRaAAAAvFQU0AbOWb-EXb3zeJzIf-FOMxE9oRRNbd4LiFDPBZdu0T68_0rcW4Q_cCvSVhI0_3QfAKHKrEu1w8s7GBPUMjiDwGjZ_ZlGt6oIL38R_72bJjO-_PSsne8E6iH5WNsPEhAaoz3VVUbbwooNqvLf2kViGhSM5Z3XM4012zAsjyrM-NU4zwMycw',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 268,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.8595495802915,
      'lng': 2.347780980291502},
     'southwest': {'lat': 48.8568516197085, 'lng': 2.345083019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '4d2e3fa9d12bf9feb685e628eaa4da9b180956a9',
   'name': 'HÃ´tel Britannique - Paris Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3168,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">HÃ´tel Britannique - Paris Louvre</a>'],
     'photo_reference': 'CmRaAAAAMCrGodIf_SADg9pAn-C-wzYqha4IsVJGUKnDiz9E_zczSVZve5O9elL2FsQ2-YTMcjUmykgk878FaxBAYlCtr8W3JYP-cD9cFlVNHam4CFG10WZFqLrRZwcVFHJFgH1uEhDV1e1uqJjfuYLzXww-M-6qGhRJcw8CxyEH4JjLH2Tn3wclLXGeQQ',
     'width': 4752}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.5,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 243,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617681302915,
      'lng': 2.348040180291502},
     'southwest': {'lat': 48.8590701697085, 'lng': 2.345342219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '9f68a76d7e95a1f94ca131a0511bfe5ffa306818',
   'name': 'Citadines Les Halles Paris (Apart Hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 496,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart Hotel Paris)</a>'],
     'photo_reference': 'CmRaAAAAD5rdIm1YoMlnafaKy4v6y5uwZQioywEqyBVKEZKBOjtICW1JWt2DM1lNX1y9SNgkayueyUFy2-j5qpzk1IFMbuyRbkyIE13TVr8O-XvuVocevyZXxJmIw7QFXSIOQu3AEhCXqldlvoJVT1EienlygAwlGhSdJl7dug8GucqH6fR28oCzWy3LrQ',
     'width': 745}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 787,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86034799999999, 'lng': 2.344054},
    'viewport': {'northeast': {'lat': 48.8616503302915,
      'lng': 2.345521080291502},
     'southwest': {'lat': 48.8589523697085, 'lng': 2.342823119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '071875f44126b9c8284f24b598fdfce0ef2b15a8',
   'name': 'HÃ´tel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 541,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107719756100811268710">larisa khramchenko</a>'],
     'photo_reference': 'CmRaAAAAEb2THwIUNq4jWXDGzm7F6kjA6EhyyIHCaB86o8auR_WaNqR8Cg1TP2XuIcK8pxpNEv-2JgSgdFWsyQ0XPJ6tMhdGqOmlnyVTOog7KHL7Ybm33hqbodneGzhSMYNQNx1qEhCihoQuUXGD54ZX79Mu35zgGhRWnSlLx4mo8j-NfSHk-M_Cvjnm9w',
     'width': 960}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 263,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569042302915,
      'lng': 2.342317580291502},
     'southwest': {'lat': 48.8542062697085, 'lng': 2.339619619708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'da46237a58939495edf652bdf976bd44df477f05',
   'name': 'Citadines Saint-Germain-des-PrÃ©s Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116649065792056265685">Gilsun LEE</a>'],
     'photo_reference': 'CmRaAAAAYJVVBF5GJZZNzaPfMcuBap753uECjL8Fm9T_LjTKrxmxnPmWEM7ALGWyJj1FgB04EAWnwhviAXqTVAtwr9C3xi45reM_kgx3egUsvhqZ8AvD4pDPmgTV9vNUVaSzVy13EhBU3FGN9GPjB713Q-JQbMNeGhQOKneeCkOjQ-S0NMvnrKS3UY-nAg',
     'width': 4032}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 638,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86634659999999, 'lng': 2.36064},
    'viewport': {'northeast': {'lat': 48.8677623302915,
      'lng': 2.361952180291502},
     'southwest': {'lat': 48.86506436970851, 'lng': 2.359254219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '87ab2d184ee12f6be846d60470ed800629c99521',
   'name': 'Paris France HÃ´tel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France HÃ´tel</a>'],
     'photo_reference': 'CmRaAAAAiy5JrQkBOpXsU_TBUT5bCzXHd_eHdDCSqLFMRHGWhJ37Wl-GhDtiztQuWqepecHLWje4jyoAuZIhnK0Q5yBdf1gJfy0n4iFlzkCJambwemTP64arebVI5piBXrR1k46BEhDAgDLaKoYU19GrrIOzFW-XGhQZu62MiLal4osnwlIhnK5h3RYnOQ',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 363,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8549629, 'lng': 2.3331998},
    'viewport': {'northeast': {'lat': 48.8563231802915,
      'lng': 2.334450380291502},
     'southwest': {'lat': 48.8536252197085, 'lng': 2.331752419708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'd466793620469a720b439cf769a6f4c28217ef88',
   'name': 'HÃ´tel Bel Ami',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4377,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111426311500153571368">HÃ´tel Bel Ami</a>'],
     'photo_reference': 'CmRaAAAA5rSCtVpO7gxLMzXtdfHAxnRpcL2X9eIh3AnM8kAVslAhs5rrEqYIGGtCuOUfOZmA6pPCsm-gxZznACWxxqnoMEQpX9pP7JQVtHf3cWHGqE7M21zxVz29U7EKcMvkr-_uEhBv5au8-8LRsSTQ0Hq1orOxGhSt0xoFn49bzB3CQoZQis7WsFwing',
     'width': 6566}],
   'place_id': 'ChIJj0jPiddx5kcRnYv-p3-vfCA',
   'plus_code': {'compound_code': 'V83M+X7 Paris, France',
    'global_code': '8FW4V83M+X7'},
   'rating': 4.6,
   'reference': 'ChIJj0jPiddx5kcRnYv-p3-vfCA',
   'scope': 'GOOGLE',
   'types': ['spa',
    'lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 446,
   'vicinity': '7 Rue Saint-BenoÃ®t, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '20dd8ae8d6ad9bbbe4ea9c6caf623fa071be187f',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2828,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109066439891801774697">HÃ´tel Regina Louvre</a>'],
     'photo_reference': 'CmRaAAAAXJ7mLXBCOmDwt1oYJ7d8hKOe40dW8eUaOysSNj4a1xJObdy2-n22J-a7-p2PC4ag7tdZlbWZoyd1rXO8RWuypLQf008vTl_Dp4XuKCHYOjr9oEVCKdPBJjOYsUGatzQDEhBoNfkgmANvDvDTa3FoagT2GhQ9X8K9fMCdyJSFRxqba4Mmr1oKEA',
     'width': 4242}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 493,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84756770000001, 'lng': 2.3718501},
    'viewport': {'northeast': {'lat': 48.8488975302915,
      'lng': 2.373108630291501},
     'southwest': {'lat': 48.8461995697085, 'lng': 2.370410669708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'dd8abb1bc4b1337fc3bd3f26e92d36c9a31de2fd',
   'name': 'HÃ´tel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">HÃ´tel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'CmRaAAAA6p4kqdMSwAr6H38c7MMIHF1gI1hsVR8CAWwD_QPHg08AmeBacdzfIyUo-SIKnBefvJFEj6qRUndnwi1Jwyyi0ucBUvzaJpaafanqhq39-Gfs32zvOkQjzdtvlrJvNC3REhDmxPSqM26X5oPenNTMcWRqGhTKVN1N29w-ix69RVf55qosZPMIIg',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 374,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731394302915,
      'lng': 2.346067130291502},
     'southwest': {'lat': 48.8704414697085, 'lng': 2.343369169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '78d0f620a6cdf990371302f25505f3916839f53a',
   'name': 'HÃ´tel Corona OpÃ©ra',
   'photos': [{'height': 2592,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102510876010964977166">æ­¦çŸ³æ—¥ç™»ç¾Ž</a>'],
     'photo_reference': 'CmRaAAAAxH3S-3T-0VSNbg3x1p4bZE6SH6kYJ2zfYUobCMCugU4o-jOtLivIB8zQe0JqMyUgiE__rd-2DB93n6iwM7KMKQWAIUMKwOiGo6ps_eIddmSkPvg0okf9ouuLhfjjxYYgEhD1vZ_9iNF0EEbqQP23nw0uGhRRodhDRRMgYSziCPp12TCU4qVkhQ',
     'width': 4608}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 304,
   'vicinity': '8 CitÃ© BergÃ¨re, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423474, 'lng': 2.3632229},
    'viewport': {'northeast': {'lat': 48.8436522302915,
      'lng': 2.364706330291502},
     'southwest': {'lat': 48.8409542697085, 'lng': 2.362008369708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'c2c8e3f55bda0fd2bec95cd85db83c756bfebe2c',
   'name': 'HÃ´tel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 683,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113748802076686483057">HÃ´tel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'CmRaAAAARUrdpNkzwsGvfda8aLV-if_1CCc7eJ855qt1LleDNfLPtDHtrQnGTRH3K9zmWqTTY4yylFMbnOqCCVlX6BqEq2nOFDnr_VvE0j9ZOzpBRNNV0TAjJhGxyjB3fgFuXai9EhAuKGaAyw-kL6eNsC5hM7T8GhRa_I7yGOETl8oKf6yzEbgfff2lrw',
     'width': 1024}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 3.9,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 413,
   'vicinity': "12 Boulevard de l'HÃ´pital, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.864294, 'lng': 2.3307997},
    'viewport': {'northeast': {'lat': 48.8655772302915,
      'lng': 2.332153880291502},
     'southwest': {'lat': 48.8628792697085, 'lng': 2.329455919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '50797fba20cc1e735c57820607b18b04abf162b9',
   'name': 'Saint James Albany Paris HÃ´tel Spa',
   'photos': [{'height': 650,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris HÃ´tel Spa</a>'],
     'photo_reference': 'CmRaAAAA3I-UBJOzOa9-1IssAuZt0Xp8ukFr1Md7XhFtOdLCG-mGrRUkp_ibWW1kugRUIC2B45YA_lBlvFLu2-gjf-wya66oHLrWrNlLrVAHRybTU_3qAWolwMRlI21oETHm1AMVEhD85iqDy6Z22w9D3PZkAWvoGhRNjrztBokuPcY5ab2sH07ugwlbCg',
     'width': 802}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['spa',
    'lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1067,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.87241758029149,
      'lng': 2.340357630291502},
     'southwest': {'lat': 48.8697196197085, 'lng': 2.337659669708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'ef15575a5c2adf57431313a0af490a78350630a5',
   'name': 'HÃ´tel IcÃ´ne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">HÃ´tel IcÃ´ne</a>'],
     'photo_reference': 'CmRaAAAAT_RRjDZCgjFnWDpa0EcCiw9_SjTlic2im7W2CKN6fKyxai-L3MFDUCDm3QJbqzcEpKO9XZgs_2zhbpnwLI4VlQprnZTLwDA8yAJ59w5RYAsHPuwOafpWQ5iUhDWr4DaFEhDru_PGXY48CiY1rRmg1PE2GhTfAD6nWzGRq53FvSj6Vtwaa6D3HA',
     'width': 1600}],
   'place_id': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'plus_code': {'compound_code': 'V8CQ+CH Paris, France',
    'global_code': '8FW4V8CQ+CH'},
   'rating': 3.7,
   'reference': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 134,
   'vicinity': "4 Rue d'Amboise, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86038899999999, 'lng': 2.323112},
    'viewport': {'northeast': {'lat': 48.8617804302915,
      'lng': 2.324489280291502},
     'southwest': {'lat': 48.8590824697085, 'lng': 2.321791319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '7f368d30dd657e11d235029a91f97fb176c9bc9a',
   'name': "HÃ´tel 4 Ã©toiles d'Orsay Paris 7Ã¨me - Esprit de France",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104203164534336742140">Mitzie Mee</a>'],
     'photo_reference': 'CmRaAAAAcZfwcq6sIjTrUis6c1uYC95E_smXbTNI0oQFVZuwdctSQYQXBXsSo_HjtD8kax4jzMhzPH2J0eUb84Ye-BDUmb_xgsApWEPqpUzGBU2wyanN3-yhcjbzS7JNX_gqRGwMEhDyV7MwRPE0uPQtNJYFDVinGhQDTOvW78ogi9K7RLOUV76xtN-o-g',
     'width': 3024}],
   'place_id': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'plus_code': {'compound_code': 'V86F+56 Paris, France',
    'global_code': '8FW4V86F+56'},
   'rating': 4.6,
   'reference': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 207,
   'vicinity': '93 Rue de Lille, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8661363, 'lng': 2.3260648},
    'viewport': {'northeast': {'lat': 48.8674534302915,
      'lng': 2.327513280291502},
     'southwest': {'lat': 48.8647554697085, 'lng': 2.324815319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '3706e8da44cbce856612cc5e666bd4e25076a0d8',
   'name': 'HÃ´tel Mayfair Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1365,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113789389085635834164">HÃ´tel Mayfair Paris</a>'],
     'photo_reference': 'CmRaAAAANMvRihSPlzzNuZLRK8NG0IEgqJWOFEzgj8XQko-B_br7o4kD5sBKJJ02BXNhmtmxG3naACY4uGvuaiz3a0qEsyIhbf75Z1nFjIBexItqjuy0bVH-BALwVfzyRV2-nKi0EhD9DMaRO9xWjCLIrcMmUnVGGhQ14WCcPx9PWj8lts9DabBAx9qliA',
     'width': 2048}],
   'place_id': 'ChIJTXVIhS1u5kcRlm9-RG0srQs',
   'plus_code': {'compound_code': 'V88G+FC Paris, France',
    'global_code': '8FW4V88G+FC'},
   'rating': 4.2,
   'reference': 'ChIJTXVIhS1u5kcRlm9-RG0srQs',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 245,
   'vicinity': '3 Rue Rouget de Lisle, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8758937, 'lng': 2.3591167},
    'viewport': {'northeast': {'lat': 48.8772989802915,
      'lng': 2.360423530291502},
     'southwest': {'lat': 48.8746010197085, 'lng': 2.357725569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '243057f371f2061f228c750901650cd7fb66d5e3',
   'name': "Holiday Inn Paris - Gare de l'Est",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1366,

In [37]:
len(hotels["results"])
#To retrieve more hotels, use the next_page_token, as it states in the Google Maps documentation.

20

In [38]:
# to retrieve the name of the first hotel in the 'results' dictionary
hotels["results"][0]["name"]

'HÃ´tel Duo'

In [45]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
# Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError, IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [46]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
3,Vaini,TO,78.80,-21.20,-175.20,Keleti Beach Resort
4,Bathsheba,BB,86.00,13.22,-59.52,Atlantis Hotel
7,Mahebourg,MU,78.80,-20.41,57.70,Shandrani Beachcomber Resort & Spa
8,Hithadhoo,MV,85.10,-0.60,73.08,Scoop Guest House
15,San Cristobal,VE,84.20,7.77,-72.22,Pirineos
16,Georgetown,MY,84.20,5.41,100.34,Cititel Penang
19,Banjar,ID,80.60,-8.19,114.97,The Hamsa Resort
22,Grand Gaube,MU,78.01,-20.01,57.66,Veranda Paul et Virginie Hotel & Spa
23,Hermanus,ZA,81.00,-34.42,19.23,Misty Waves Boutique Hotel
24,Cape Town,ZA,79.00,-33.93,18.42,Southern Sun Waterfront Cape Town

In [47]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [55]:

# info_box_template = """
# <dl>
# <dt>Name</dt><dd>{column1}</dd>
# <dt>Another name</dt><dd>{column2}</dd>
# </dl>
# """


# the syntax is markers = gmaps.marker_layer(marker_locations), where the marker_locations are latitudes and longitudes.
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [53]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# The <dl> tag is a description list (dl).
# The <dt> tag is a term or name in a description list that is nested under the <dl> tag.
# The <dd> tag is used to define the term or name or <dt> tag.

# info_box_template = """
# <dl>
# <dt>Name</dt><dd>{column1}</dd>
# <dt>Another name</dt><dd>{column2}</dd>
# </dl>
# """